package com.knowledgewalls.models;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.Table;


@Entity
@Inheritance
@DiscriminatorColumn(name = "user_type")
@Table(name = "users")
public abstract class User {

  // ==============
  // PRIVATE FIELDS
  // ==============
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user email

  private String email;
  
  // ==============
  // PUBLIC METHODS
  // ==============
  

  public long getId() {
    return id;
  }

  public String getEmail() {
    return email;
  }


  public void setId(long id) {
    this.id = id;
  }

 
  public void setEmail(String email) {
    this.email = email;
  }

} // class User